title: Dynamic Campaign Tools
tagline: Dynamic Campaigns for DCS
description: Mission scripting framework for persistent Digital Combat Simulator (DCS) missions.
remote_theme: pmarsceill/just-the-docs
github_link: "https://github.com/team-limakilo/dct"
discord_link: "https://discord.gg/dPG9pNuxJc"
dct_discord_link: "https://discord.gg/kG38MDqDrN"
release_link: "https://nightly.link/team-limakilo/dct/workflows/dev-builds/master"
aux_links_new_tab: true
aux_links:
        "Main DCT Codebase":
                - "https://github.com/jtoppins/dct"
        "Contact Us":
                - "https://discord.gg/kG38MDqDrN"
color_scheme: dark
